stages:
  - build

variables:
  FF_USE_FASTZIP: 1
  CACHE_COMPRESSION_LEVEL: "fastest"

build:
  stage: build
  image: registry.gitlab.tigers-mannheim.de/main/tigers-buildroot/ubuntu:rpi-24.04
  script:
    - cmake -B build -DCMAKE_SYSROOT=/opt/pizero2w-tigers-sysroot -DCMAKE_PREFIX_PATH=/opt/arm-none-linux-gnueabihf .
    - cmake --build build -j
  artifacts:
    expire_in: 1 hrs
    name: ssl-tracking-cam-build-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths:
      - build

build-image:
  stage: build
  image: registry.gitlab.tigers-mannheim.de/main/tigers-buildroot/ubuntu:cxxDev-24.04
  tags:
    - buildroot  
  cache:
    key: rpi3-buildroot
    paths:
      - tigers-buildroot/buildroot-ccache
      - tigers-buildroot/buildroot-dl
    when: 'always'
  script:
    - git clone --branch master --single-branch https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.tigers-mannheim.de/main/tigers-buildroot.git tigers-buildroot-clone
    - mkdir -p tigers-buildroot
    - rsync -a tigers-buildroot-clone/ tigers-buildroot/
    - cd tigers-buildroot
    - git submodule update --init
    - rm -rf tigers/package/cam
    - git clone --branch $CI_COMMIT_REF_NAME --single-branch --recursive https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.tigers-mannheim.de/AndreR/ssl-tracking-cam.git tigers/package/cam
    - echo -e '\nsource "$BR2_EXTERNAL_TIGERS_PATH/package/cam/Config.in"' >> tigers/Config.in
    - echo -e '\nBR2_PACKAGE_SSL_TRACKING_CAM=y' >> tigers/configs/pizero2w_defconfig
    - cat tigers/Config.in
    - cat tigers/configs/pizero2w_defconfig
    - export BR2_CCACHE_DIR="$PWD/buildroot-ccache"
    - cd buildroot
    - make BR2_EXTERNAL=../tigers pizero2w_defconfig
    - make clean
    - make -j6
    - cd ../..
    - 'echo "ssl-tracking-cam: $CI_COMMIT_REF_NAME ($CI_COMMIT_SHA)" >> versions'
    - mkdir -p ssl-tracking-cam
    - mv tigers-buildroot/tigers/output/pizero2w/images/sdcard.img ssl-tracking-cam/sdcard.img
    - mv tigers-buildroot/tigers/output/pizero2w/images/update.squashfs ssl-tracking-cam/update.squashfs
  artifacts:
    name: ssl-tracking-cam-image-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    paths:
      - ssl-tracking-cam
      - versions
  only:
    - tags
    - master
