// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages_robocup_ssl_wrapper_tracked.proto
// Protobuf C++ Version: 5.29.3

#ifndef messages_5frobocup_5fssl_5fwrapper_5ftracked_2eproto_2epb_2eh
#define messages_5frobocup_5fssl_5fwrapper_5ftracked_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "messages_robocup_ssl_detection_tracked.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_messages_5frobocup_5fssl_5fwrapper_5ftracked_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_5frobocup_5fssl_5fwrapper_5ftracked_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_messages_5frobocup_5fssl_5fwrapper_5ftracked_2eproto;
class TrackerWrapperPacket;
struct TrackerWrapperPacketDefaultTypeInternal;
extern TrackerWrapperPacketDefaultTypeInternal _TrackerWrapperPacket_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class TrackerWrapperPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:TrackerWrapperPacket) */ {
 public:
  inline TrackerWrapperPacket() : TrackerWrapperPacket(nullptr) {}
  ~TrackerWrapperPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(TrackerWrapperPacket* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(TrackerWrapperPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR TrackerWrapperPacket(
      ::google::protobuf::internal::ConstantInitialized);

  inline TrackerWrapperPacket(const TrackerWrapperPacket& from) : TrackerWrapperPacket(nullptr, from) {}
  inline TrackerWrapperPacket(TrackerWrapperPacket&& from) noexcept
      : TrackerWrapperPacket(nullptr, std::move(from)) {}
  inline TrackerWrapperPacket& operator=(const TrackerWrapperPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline TrackerWrapperPacket& operator=(TrackerWrapperPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TrackerWrapperPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const TrackerWrapperPacket* internal_default_instance() {
    return reinterpret_cast<const TrackerWrapperPacket*>(
        &_TrackerWrapperPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(TrackerWrapperPacket& a, TrackerWrapperPacket& b) { a.Swap(&b); }
  inline void Swap(TrackerWrapperPacket* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TrackerWrapperPacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TrackerWrapperPacket* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<TrackerWrapperPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const TrackerWrapperPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const TrackerWrapperPacket& from) { TrackerWrapperPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(TrackerWrapperPacket* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "TrackerWrapperPacket"; }

 protected:
  explicit TrackerWrapperPacket(::google::protobuf::Arena* arena);
  TrackerWrapperPacket(::google::protobuf::Arena* arena, const TrackerWrapperPacket& from);
  TrackerWrapperPacket(::google::protobuf::Arena* arena, TrackerWrapperPacket&& from) noexcept
      : TrackerWrapperPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUuidFieldNumber = 1,
    kSourceNameFieldNumber = 2,
    kTrackedFrameFieldNumber = 3,
  };
  // required string uuid = 1;
  bool has_uuid() const;
  void clear_uuid() ;
  const std::string& uuid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* value);

  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(
      const std::string& value);
  std::string* _internal_mutable_uuid();

  public:
  // optional string source_name = 2;
  bool has_source_name() const;
  void clear_source_name() ;
  const std::string& source_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_source_name(Arg_&& arg, Args_... args);
  std::string* mutable_source_name();
  PROTOBUF_NODISCARD std::string* release_source_name();
  void set_allocated_source_name(std::string* value);

  private:
  const std::string& _internal_source_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_source_name(
      const std::string& value);
  std::string* _internal_mutable_source_name();

  public:
  // optional .TrackedFrame tracked_frame = 3;
  bool has_tracked_frame() const;
  void clear_tracked_frame() ;
  const ::TrackedFrame& tracked_frame() const;
  PROTOBUF_NODISCARD ::TrackedFrame* release_tracked_frame();
  ::TrackedFrame* mutable_tracked_frame();
  void set_allocated_tracked_frame(::TrackedFrame* value);
  void unsafe_arena_set_allocated_tracked_frame(::TrackedFrame* value);
  ::TrackedFrame* unsafe_arena_release_tracked_frame();

  private:
  const ::TrackedFrame& _internal_tracked_frame() const;
  ::TrackedFrame* _internal_mutable_tracked_frame();

  public:
  // @@protoc_insertion_point(class_scope:TrackerWrapperPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 1,
      44, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const TrackerWrapperPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    ::google::protobuf::internal::ArenaStringPtr source_name_;
    ::TrackedFrame* tracked_frame_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_5frobocup_5fssl_5fwrapper_5ftracked_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TrackerWrapperPacket

// required string uuid = 1;
inline bool TrackerWrapperPacket::has_uuid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void TrackerWrapperPacket::clear_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uuid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TrackerWrapperPacket::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TrackerWrapperPacket.uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TrackerWrapperPacket::set_uuid(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:TrackerWrapperPacket.uuid)
}
inline std::string* TrackerWrapperPacket::mutable_uuid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:TrackerWrapperPacket.uuid)
  return _s;
}
inline const std::string& TrackerWrapperPacket::_internal_uuid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uuid_.Get();
}
inline void TrackerWrapperPacket::_internal_set_uuid(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.uuid_.Set(value, GetArena());
}
inline std::string* TrackerWrapperPacket::_internal_mutable_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.uuid_.Mutable( GetArena());
}
inline std::string* TrackerWrapperPacket::release_uuid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:TrackerWrapperPacket.uuid)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.uuid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.uuid_.Set("", GetArena());
  }
  return released;
}
inline void TrackerWrapperPacket::set_allocated_uuid(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.uuid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uuid_.IsDefault()) {
    _impl_.uuid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:TrackerWrapperPacket.uuid)
}

// optional string source_name = 2;
inline bool TrackerWrapperPacket::has_source_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void TrackerWrapperPacket::clear_source_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.source_name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& TrackerWrapperPacket::source_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TrackerWrapperPacket.source_name)
  return _internal_source_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void TrackerWrapperPacket::set_source_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.source_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:TrackerWrapperPacket.source_name)
}
inline std::string* TrackerWrapperPacket::mutable_source_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_source_name();
  // @@protoc_insertion_point(field_mutable:TrackerWrapperPacket.source_name)
  return _s;
}
inline const std::string& TrackerWrapperPacket::_internal_source_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.source_name_.Get();
}
inline void TrackerWrapperPacket::_internal_set_source_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.source_name_.Set(value, GetArena());
}
inline std::string* TrackerWrapperPacket::_internal_mutable_source_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.source_name_.Mutable( GetArena());
}
inline std::string* TrackerWrapperPacket::release_source_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:TrackerWrapperPacket.source_name)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.source_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.source_name_.Set("", GetArena());
  }
  return released;
}
inline void TrackerWrapperPacket::set_allocated_source_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.source_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.source_name_.IsDefault()) {
    _impl_.source_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:TrackerWrapperPacket.source_name)
}

// optional .TrackedFrame tracked_frame = 3;
inline bool TrackerWrapperPacket::has_tracked_frame() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.tracked_frame_ != nullptr);
  return value;
}
inline const ::TrackedFrame& TrackerWrapperPacket::_internal_tracked_frame() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::TrackedFrame* p = _impl_.tracked_frame_;
  return p != nullptr ? *p : reinterpret_cast<const ::TrackedFrame&>(::_TrackedFrame_default_instance_);
}
inline const ::TrackedFrame& TrackerWrapperPacket::tracked_frame() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:TrackerWrapperPacket.tracked_frame)
  return _internal_tracked_frame();
}
inline void TrackerWrapperPacket::unsafe_arena_set_allocated_tracked_frame(::TrackedFrame* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.tracked_frame_);
  }
  _impl_.tracked_frame_ = reinterpret_cast<::TrackedFrame*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:TrackerWrapperPacket.tracked_frame)
}
inline ::TrackedFrame* TrackerWrapperPacket::release_tracked_frame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::TrackedFrame* released = _impl_.tracked_frame_;
  _impl_.tracked_frame_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::TrackedFrame* TrackerWrapperPacket::unsafe_arena_release_tracked_frame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:TrackerWrapperPacket.tracked_frame)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::TrackedFrame* temp = _impl_.tracked_frame_;
  _impl_.tracked_frame_ = nullptr;
  return temp;
}
inline ::TrackedFrame* TrackerWrapperPacket::_internal_mutable_tracked_frame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.tracked_frame_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::TrackedFrame>(GetArena());
    _impl_.tracked_frame_ = reinterpret_cast<::TrackedFrame*>(p);
  }
  return _impl_.tracked_frame_;
}
inline ::TrackedFrame* TrackerWrapperPacket::mutable_tracked_frame() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000004u;
  ::TrackedFrame* _msg = _internal_mutable_tracked_frame();
  // @@protoc_insertion_point(field_mutable:TrackerWrapperPacket.tracked_frame)
  return _msg;
}
inline void TrackerWrapperPacket::set_allocated_tracked_frame(::TrackedFrame* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.tracked_frame_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.tracked_frame_ = reinterpret_cast<::TrackedFrame*>(value);
  // @@protoc_insertion_point(field_set_allocated:TrackerWrapperPacket.tracked_frame)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // messages_5frobocup_5fssl_5fwrapper_5ftracked_2eproto_2epb_2eh
