/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_geometry.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages_robocup_ssl_geometry.pb-c.h"
void   vector2f__init
                     (Vector2f         *message)
{
  static const Vector2f init_value = VECTOR2F__INIT;
  *message = init_value;
}
size_t vector2f__get_packed_size
                     (const Vector2f *message)
{
  assert(message->base.descriptor == &vector2f__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vector2f__pack
                     (const Vector2f *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vector2f__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vector2f__pack_to_buffer
                     (const Vector2f *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vector2f__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vector2f *
       vector2f__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vector2f *)
     protobuf_c_message_unpack (&vector2f__descriptor,
                                allocator, len, data);
}
void   vector2f__free_unpacked
                     (Vector2f *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vector2f__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__field_line_segment__init
                     (SSLFieldLineSegment         *message)
{
  static const SSLFieldLineSegment init_value = SSL__FIELD_LINE_SEGMENT__INIT;
  *message = init_value;
}
size_t ssl__field_line_segment__get_packed_size
                     (const SSLFieldLineSegment *message)
{
  assert(message->base.descriptor == &ssl__field_line_segment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__field_line_segment__pack
                     (const SSLFieldLineSegment *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__field_line_segment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__field_line_segment__pack_to_buffer
                     (const SSLFieldLineSegment *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__field_line_segment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLFieldLineSegment *
       ssl__field_line_segment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLFieldLineSegment *)
     protobuf_c_message_unpack (&ssl__field_line_segment__descriptor,
                                allocator, len, data);
}
void   ssl__field_line_segment__free_unpacked
                     (SSLFieldLineSegment *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssl__field_line_segment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__field_circular_arc__init
                     (SSLFieldCircularArc         *message)
{
  static const SSLFieldCircularArc init_value = SSL__FIELD_CIRCULAR_ARC__INIT;
  *message = init_value;
}
size_t ssl__field_circular_arc__get_packed_size
                     (const SSLFieldCircularArc *message)
{
  assert(message->base.descriptor == &ssl__field_circular_arc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__field_circular_arc__pack
                     (const SSLFieldCircularArc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__field_circular_arc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__field_circular_arc__pack_to_buffer
                     (const SSLFieldCircularArc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__field_circular_arc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLFieldCircularArc *
       ssl__field_circular_arc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLFieldCircularArc *)
     protobuf_c_message_unpack (&ssl__field_circular_arc__descriptor,
                                allocator, len, data);
}
void   ssl__field_circular_arc__free_unpacked
                     (SSLFieldCircularArc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssl__field_circular_arc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__geometry_field_size__init
                     (SSLGeometryFieldSize         *message)
{
  static const SSLGeometryFieldSize init_value = SSL__GEOMETRY_FIELD_SIZE__INIT;
  *message = init_value;
}
size_t ssl__geometry_field_size__get_packed_size
                     (const SSLGeometryFieldSize *message)
{
  assert(message->base.descriptor == &ssl__geometry_field_size__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__geometry_field_size__pack
                     (const SSLGeometryFieldSize *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__geometry_field_size__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__geometry_field_size__pack_to_buffer
                     (const SSLGeometryFieldSize *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__geometry_field_size__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLGeometryFieldSize *
       ssl__geometry_field_size__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLGeometryFieldSize *)
     protobuf_c_message_unpack (&ssl__geometry_field_size__descriptor,
                                allocator, len, data);
}
void   ssl__geometry_field_size__free_unpacked
                     (SSLGeometryFieldSize *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssl__geometry_field_size__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__geometry_camera_calibration__init
                     (SSLGeometryCameraCalibration         *message)
{
  static const SSLGeometryCameraCalibration init_value = SSL__GEOMETRY_CAMERA_CALIBRATION__INIT;
  *message = init_value;
}
size_t ssl__geometry_camera_calibration__get_packed_size
                     (const SSLGeometryCameraCalibration *message)
{
  assert(message->base.descriptor == &ssl__geometry_camera_calibration__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__geometry_camera_calibration__pack
                     (const SSLGeometryCameraCalibration *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__geometry_camera_calibration__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__geometry_camera_calibration__pack_to_buffer
                     (const SSLGeometryCameraCalibration *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__geometry_camera_calibration__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLGeometryCameraCalibration *
       ssl__geometry_camera_calibration__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLGeometryCameraCalibration *)
     protobuf_c_message_unpack (&ssl__geometry_camera_calibration__descriptor,
                                allocator, len, data);
}
void   ssl__geometry_camera_calibration__free_unpacked
                     (SSLGeometryCameraCalibration *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssl__geometry_camera_calibration__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__ball_model_straight_two_phase__init
                     (SSLBallModelStraightTwoPhase         *message)
{
  static const SSLBallModelStraightTwoPhase init_value = SSL__BALL_MODEL_STRAIGHT_TWO_PHASE__INIT;
  *message = init_value;
}
size_t ssl__ball_model_straight_two_phase__get_packed_size
                     (const SSLBallModelStraightTwoPhase *message)
{
  assert(message->base.descriptor == &ssl__ball_model_straight_two_phase__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__ball_model_straight_two_phase__pack
                     (const SSLBallModelStraightTwoPhase *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__ball_model_straight_two_phase__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__ball_model_straight_two_phase__pack_to_buffer
                     (const SSLBallModelStraightTwoPhase *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__ball_model_straight_two_phase__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLBallModelStraightTwoPhase *
       ssl__ball_model_straight_two_phase__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLBallModelStraightTwoPhase *)
     protobuf_c_message_unpack (&ssl__ball_model_straight_two_phase__descriptor,
                                allocator, len, data);
}
void   ssl__ball_model_straight_two_phase__free_unpacked
                     (SSLBallModelStraightTwoPhase *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssl__ball_model_straight_two_phase__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__ball_model_chip_fixed_loss__init
                     (SSLBallModelChipFixedLoss         *message)
{
  static const SSLBallModelChipFixedLoss init_value = SSL__BALL_MODEL_CHIP_FIXED_LOSS__INIT;
  *message = init_value;
}
size_t ssl__ball_model_chip_fixed_loss__get_packed_size
                     (const SSLBallModelChipFixedLoss *message)
{
  assert(message->base.descriptor == &ssl__ball_model_chip_fixed_loss__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__ball_model_chip_fixed_loss__pack
                     (const SSLBallModelChipFixedLoss *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__ball_model_chip_fixed_loss__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__ball_model_chip_fixed_loss__pack_to_buffer
                     (const SSLBallModelChipFixedLoss *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__ball_model_chip_fixed_loss__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLBallModelChipFixedLoss *
       ssl__ball_model_chip_fixed_loss__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLBallModelChipFixedLoss *)
     protobuf_c_message_unpack (&ssl__ball_model_chip_fixed_loss__descriptor,
                                allocator, len, data);
}
void   ssl__ball_model_chip_fixed_loss__free_unpacked
                     (SSLBallModelChipFixedLoss *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssl__ball_model_chip_fixed_loss__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__geometry_models__init
                     (SSLGeometryModels         *message)
{
  static const SSLGeometryModels init_value = SSL__GEOMETRY_MODELS__INIT;
  *message = init_value;
}
size_t ssl__geometry_models__get_packed_size
                     (const SSLGeometryModels *message)
{
  assert(message->base.descriptor == &ssl__geometry_models__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__geometry_models__pack
                     (const SSLGeometryModels *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__geometry_models__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__geometry_models__pack_to_buffer
                     (const SSLGeometryModels *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__geometry_models__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLGeometryModels *
       ssl__geometry_models__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLGeometryModels *)
     protobuf_c_message_unpack (&ssl__geometry_models__descriptor,
                                allocator, len, data);
}
void   ssl__geometry_models__free_unpacked
                     (SSLGeometryModels *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssl__geometry_models__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ssl__geometry_data__init
                     (SSLGeometryData         *message)
{
  static const SSLGeometryData init_value = SSL__GEOMETRY_DATA__INIT;
  *message = init_value;
}
size_t ssl__geometry_data__get_packed_size
                     (const SSLGeometryData *message)
{
  assert(message->base.descriptor == &ssl__geometry_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__geometry_data__pack
                     (const SSLGeometryData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__geometry_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__geometry_data__pack_to_buffer
                     (const SSLGeometryData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__geometry_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLGeometryData *
       ssl__geometry_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLGeometryData *)
     protobuf_c_message_unpack (&ssl__geometry_data__descriptor,
                                allocator, len, data);
}
void   ssl__geometry_data__free_unpacked
                     (SSLGeometryData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssl__geometry_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor vector2f__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vector2f, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vector2f, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vector2f__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange vector2f__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vector2f__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Vector2f",
  "Vector2f",
  "Vector2f",
  "",
  sizeof(Vector2f),
  2,
  vector2f__field_descriptors,
  vector2f__field_indices_by_name,
  1,  vector2f__number_ranges,
  (ProtobufCMessageInit) vector2f__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__field_line_segment__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SSLFieldLineSegment, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "p1",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLFieldLineSegment, p1),
    &vector2f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "p2",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLFieldLineSegment, p2),
    &vector2f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thickness",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLFieldLineSegment, thickness),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SSLFieldLineSegment, has_type),
    offsetof(SSLFieldLineSegment, type),
    &ssl__field_shape_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__field_line_segment__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = p1 */
  2,   /* field[2] = p2 */
  3,   /* field[3] = thickness */
  4,   /* field[4] = type */
};
static const ProtobufCIntRange ssl__field_line_segment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ssl__field_line_segment__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_FieldLineSegment",
  "SSLFieldLineSegment",
  "SSLFieldLineSegment",
  "",
  sizeof(SSLFieldLineSegment),
  5,
  ssl__field_line_segment__field_descriptors,
  ssl__field_line_segment__field_indices_by_name,
  1,  ssl__field_line_segment__number_ranges,
  (ProtobufCMessageInit) ssl__field_line_segment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__field_circular_arc__field_descriptors[7] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SSLFieldCircularArc, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "center",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLFieldCircularArc, center),
    &vector2f__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "radius",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLFieldCircularArc, radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a1",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLFieldCircularArc, a1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a2",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLFieldCircularArc, a2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thickness",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLFieldCircularArc, thickness),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SSLFieldCircularArc, has_type),
    offsetof(SSLFieldCircularArc, type),
    &ssl__field_shape_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__field_circular_arc__field_indices_by_name[] = {
  3,   /* field[3] = a1 */
  4,   /* field[4] = a2 */
  1,   /* field[1] = center */
  0,   /* field[0] = name */
  2,   /* field[2] = radius */
  5,   /* field[5] = thickness */
  6,   /* field[6] = type */
};
static const ProtobufCIntRange ssl__field_circular_arc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ssl__field_circular_arc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_FieldCircularArc",
  "SSLFieldCircularArc",
  "SSLFieldCircularArc",
  "",
  sizeof(SSLFieldCircularArc),
  7,
  ssl__field_circular_arc__field_descriptors,
  ssl__field_circular_arc__field_indices_by_name,
  1,  ssl__field_circular_arc__number_ranges,
  (ProtobufCMessageInit) ssl__field_circular_arc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__geometry_field_size__field_descriptors[17] =
{
  {
    "field_length",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryFieldSize, field_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field_width",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryFieldSize, field_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "goal_width",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryFieldSize, goal_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "goal_depth",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryFieldSize, goal_depth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boundary_width",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryFieldSize, boundary_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field_lines",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SSLGeometryFieldSize, n_field_lines),
    offsetof(SSLGeometryFieldSize, field_lines),
    &ssl__field_line_segment__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "field_arcs",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SSLGeometryFieldSize, n_field_arcs),
    offsetof(SSLGeometryFieldSize, field_arcs),
    &ssl__field_circular_arc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "penalty_area_depth",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SSLGeometryFieldSize, has_penalty_area_depth),
    offsetof(SSLGeometryFieldSize, penalty_area_depth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "penalty_area_width",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SSLGeometryFieldSize, has_penalty_area_width),
    offsetof(SSLGeometryFieldSize, penalty_area_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "center_circle_radius",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SSLGeometryFieldSize, has_center_circle_radius),
    offsetof(SSLGeometryFieldSize, center_circle_radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "line_thickness",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SSLGeometryFieldSize, has_line_thickness),
    offsetof(SSLGeometryFieldSize, line_thickness),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "goal_center_to_penalty_mark",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SSLGeometryFieldSize, has_goal_center_to_penalty_mark),
    offsetof(SSLGeometryFieldSize, goal_center_to_penalty_mark),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "goal_height",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SSLGeometryFieldSize, has_goal_height),
    offsetof(SSLGeometryFieldSize, goal_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ball_radius",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SSLGeometryFieldSize, has_ball_radius),
    offsetof(SSLGeometryFieldSize, ball_radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_robot_radius",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SSLGeometryFieldSize, has_max_robot_radius),
    offsetof(SSLGeometryFieldSize, max_robot_radius),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boundary_width_goal_line",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SSLGeometryFieldSize, has_boundary_width_goal_line),
    offsetof(SSLGeometryFieldSize, boundary_width_goal_line),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "goal_substitution_area_width",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SSLGeometryFieldSize, has_goal_substitution_area_width),
    offsetof(SSLGeometryFieldSize, goal_substitution_area_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__geometry_field_size__field_indices_by_name[] = {
  13,   /* field[13] = ball_radius */
  4,   /* field[4] = boundary_width */
  15,   /* field[15] = boundary_width_goal_line */
  9,   /* field[9] = center_circle_radius */
  6,   /* field[6] = field_arcs */
  0,   /* field[0] = field_length */
  5,   /* field[5] = field_lines */
  1,   /* field[1] = field_width */
  11,   /* field[11] = goal_center_to_penalty_mark */
  3,   /* field[3] = goal_depth */
  12,   /* field[12] = goal_height */
  16,   /* field[16] = goal_substitution_area_width */
  2,   /* field[2] = goal_width */
  10,   /* field[10] = line_thickness */
  14,   /* field[14] = max_robot_radius */
  7,   /* field[7] = penalty_area_depth */
  8,   /* field[8] = penalty_area_width */
};
static const ProtobufCIntRange ssl__geometry_field_size__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor ssl__geometry_field_size__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_GeometryFieldSize",
  "SSLGeometryFieldSize",
  "SSLGeometryFieldSize",
  "",
  sizeof(SSLGeometryFieldSize),
  17,
  ssl__geometry_field_size__field_descriptors,
  ssl__geometry_field_size__field_indices_by_name,
  1,  ssl__geometry_field_size__number_ranges,
  (ProtobufCMessageInit) ssl__geometry_field_size__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__geometry_camera_calibration__field_descriptors[17] =
{
  {
    "camera_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, camera_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "focal_length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, focal_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "principal_point_x",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, principal_point_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "principal_point_y",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, principal_point_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distortion",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, distortion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q0",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, q0),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q1",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, q1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q2",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, q2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "q3",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, q3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ty",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, ty),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tz",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryCameraCalibration, tz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derived_camera_world_tx",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SSLGeometryCameraCalibration, has_derived_camera_world_tx),
    offsetof(SSLGeometryCameraCalibration, derived_camera_world_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derived_camera_world_ty",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SSLGeometryCameraCalibration, has_derived_camera_world_ty),
    offsetof(SSLGeometryCameraCalibration, derived_camera_world_ty),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derived_camera_world_tz",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SSLGeometryCameraCalibration, has_derived_camera_world_tz),
    offsetof(SSLGeometryCameraCalibration, derived_camera_world_tz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pixel_image_width",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SSLGeometryCameraCalibration, has_pixel_image_width),
    offsetof(SSLGeometryCameraCalibration, pixel_image_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pixel_image_height",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SSLGeometryCameraCalibration, has_pixel_image_height),
    offsetof(SSLGeometryCameraCalibration, pixel_image_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__geometry_camera_calibration__field_indices_by_name[] = {
  0,   /* field[0] = camera_id */
  12,   /* field[12] = derived_camera_world_tx */
  13,   /* field[13] = derived_camera_world_ty */
  14,   /* field[14] = derived_camera_world_tz */
  4,   /* field[4] = distortion */
  1,   /* field[1] = focal_length */
  16,   /* field[16] = pixel_image_height */
  15,   /* field[15] = pixel_image_width */
  2,   /* field[2] = principal_point_x */
  3,   /* field[3] = principal_point_y */
  5,   /* field[5] = q0 */
  6,   /* field[6] = q1 */
  7,   /* field[7] = q2 */
  8,   /* field[8] = q3 */
  9,   /* field[9] = tx */
  10,   /* field[10] = ty */
  11,   /* field[11] = tz */
};
static const ProtobufCIntRange ssl__geometry_camera_calibration__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor ssl__geometry_camera_calibration__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_GeometryCameraCalibration",
  "SSLGeometryCameraCalibration",
  "SSLGeometryCameraCalibration",
  "",
  sizeof(SSLGeometryCameraCalibration),
  17,
  ssl__geometry_camera_calibration__field_descriptors,
  ssl__geometry_camera_calibration__field_indices_by_name,
  1,  ssl__geometry_camera_calibration__number_ranges,
  (ProtobufCMessageInit) ssl__geometry_camera_calibration__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__ball_model_straight_two_phase__field_descriptors[3] =
{
  {
    "acc_slide",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SSLBallModelStraightTwoPhase, acc_slide),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acc_roll",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SSLBallModelStraightTwoPhase, acc_roll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "k_switch",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SSLBallModelStraightTwoPhase, k_switch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__ball_model_straight_two_phase__field_indices_by_name[] = {
  1,   /* field[1] = acc_roll */
  0,   /* field[0] = acc_slide */
  2,   /* field[2] = k_switch */
};
static const ProtobufCIntRange ssl__ball_model_straight_two_phase__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ssl__ball_model_straight_two_phase__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_BallModelStraightTwoPhase",
  "SSLBallModelStraightTwoPhase",
  "SSLBallModelStraightTwoPhase",
  "",
  sizeof(SSLBallModelStraightTwoPhase),
  3,
  ssl__ball_model_straight_two_phase__field_descriptors,
  ssl__ball_model_straight_two_phase__field_indices_by_name,
  1,  ssl__ball_model_straight_two_phase__number_ranges,
  (ProtobufCMessageInit) ssl__ball_model_straight_two_phase__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__ball_model_chip_fixed_loss__field_descriptors[3] =
{
  {
    "damping_xy_first_hop",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SSLBallModelChipFixedLoss, damping_xy_first_hop),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "damping_xy_other_hops",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SSLBallModelChipFixedLoss, damping_xy_other_hops),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "damping_z",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(SSLBallModelChipFixedLoss, damping_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__ball_model_chip_fixed_loss__field_indices_by_name[] = {
  0,   /* field[0] = damping_xy_first_hop */
  1,   /* field[1] = damping_xy_other_hops */
  2,   /* field[2] = damping_z */
};
static const ProtobufCIntRange ssl__ball_model_chip_fixed_loss__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ssl__ball_model_chip_fixed_loss__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_BallModelChipFixedLoss",
  "SSLBallModelChipFixedLoss",
  "SSLBallModelChipFixedLoss",
  "",
  sizeof(SSLBallModelChipFixedLoss),
  3,
  ssl__ball_model_chip_fixed_loss__field_descriptors,
  ssl__ball_model_chip_fixed_loss__field_indices_by_name,
  1,  ssl__ball_model_chip_fixed_loss__number_ranges,
  (ProtobufCMessageInit) ssl__ball_model_chip_fixed_loss__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__geometry_models__field_descriptors[2] =
{
  {
    "straight_two_phase",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryModels, straight_two_phase),
    &ssl__ball_model_straight_two_phase__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chip_fixed_loss",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryModels, chip_fixed_loss),
    &ssl__ball_model_chip_fixed_loss__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__geometry_models__field_indices_by_name[] = {
  1,   /* field[1] = chip_fixed_loss */
  0,   /* field[0] = straight_two_phase */
};
static const ProtobufCIntRange ssl__geometry_models__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ssl__geometry_models__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_GeometryModels",
  "SSLGeometryModels",
  "SSLGeometryModels",
  "",
  sizeof(SSLGeometryModels),
  2,
  ssl__geometry_models__field_descriptors,
  ssl__geometry_models__field_indices_by_name,
  1,  ssl__geometry_models__number_ranges,
  (ProtobufCMessageInit) ssl__geometry_models__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ssl__geometry_data__field_descriptors[3] =
{
  {
    "field",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryData, field),
    &ssl__geometry_field_size__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "calib",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SSLGeometryData, n_calib),
    offsetof(SSLGeometryData, calib),
    &ssl__geometry_camera_calibration__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "models",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLGeometryData, models),
    &ssl__geometry_models__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__geometry_data__field_indices_by_name[] = {
  1,   /* field[1] = calib */
  0,   /* field[0] = field */
  2,   /* field[2] = models */
};
static const ProtobufCIntRange ssl__geometry_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ssl__geometry_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_GeometryData",
  "SSLGeometryData",
  "SSLGeometryData",
  "",
  sizeof(SSLGeometryData),
  3,
  ssl__geometry_data__field_descriptors,
  ssl__geometry_data__field_indices_by_name,
  1,  ssl__geometry_data__number_ranges,
  (ProtobufCMessageInit) ssl__geometry_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ssl__field_shape_type__enum_values_by_number[14] =
{
  { "Undefined", "SSL__FIELD_SHAPE_TYPE__Undefined", 0 },
  { "CenterCircle", "SSL__FIELD_SHAPE_TYPE__CenterCircle", 1 },
  { "TopTouchLine", "SSL__FIELD_SHAPE_TYPE__TopTouchLine", 2 },
  { "BottomTouchLine", "SSL__FIELD_SHAPE_TYPE__BottomTouchLine", 3 },
  { "LeftGoalLine", "SSL__FIELD_SHAPE_TYPE__LeftGoalLine", 4 },
  { "RightGoalLine", "SSL__FIELD_SHAPE_TYPE__RightGoalLine", 5 },
  { "HalfwayLine", "SSL__FIELD_SHAPE_TYPE__HalfwayLine", 6 },
  { "CenterLine", "SSL__FIELD_SHAPE_TYPE__CenterLine", 7 },
  { "LeftPenaltyStretch", "SSL__FIELD_SHAPE_TYPE__LeftPenaltyStretch", 8 },
  { "RightPenaltyStretch", "SSL__FIELD_SHAPE_TYPE__RightPenaltyStretch", 9 },
  { "LeftFieldLeftPenaltyStretch", "SSL__FIELD_SHAPE_TYPE__LeftFieldLeftPenaltyStretch", 10 },
  { "LeftFieldRightPenaltyStretch", "SSL__FIELD_SHAPE_TYPE__LeftFieldRightPenaltyStretch", 11 },
  { "RightFieldLeftPenaltyStretch", "SSL__FIELD_SHAPE_TYPE__RightFieldLeftPenaltyStretch", 12 },
  { "RightFieldRightPenaltyStretch", "SSL__FIELD_SHAPE_TYPE__RightFieldRightPenaltyStretch", 13 },
};
static const ProtobufCIntRange ssl__field_shape_type__value_ranges[] = {
{0, 0},{0, 14}
};
static const ProtobufCEnumValueIndex ssl__field_shape_type__enum_values_by_name[14] =
{
  { "BottomTouchLine", 3 },
  { "CenterCircle", 1 },
  { "CenterLine", 7 },
  { "HalfwayLine", 6 },
  { "LeftFieldLeftPenaltyStretch", 10 },
  { "LeftFieldRightPenaltyStretch", 11 },
  { "LeftGoalLine", 4 },
  { "LeftPenaltyStretch", 8 },
  { "RightFieldLeftPenaltyStretch", 12 },
  { "RightFieldRightPenaltyStretch", 13 },
  { "RightGoalLine", 5 },
  { "RightPenaltyStretch", 9 },
  { "TopTouchLine", 2 },
  { "Undefined", 0 },
};
const ProtobufCEnumDescriptor ssl__field_shape_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SSL_FieldShapeType",
  "SSL_FieldShapeType",
  "SSLFieldShapeType",
  "",
  14,
  ssl__field_shape_type__enum_values_by_number,
  14,
  ssl__field_shape_type__enum_values_by_name,
  1,
  ssl__field_shape_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
