/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_detection_tracked.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages_robocup_ssl_detection_tracked.pb-c.h"
void   vector2__init
                     (Vector2         *message)
{
  static const Vector2 init_value = VECTOR2__INIT;
  *message = init_value;
}
size_t vector2__get_packed_size
                     (const Vector2 *message)
{
  assert(message->base.descriptor == &vector2__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vector2__pack
                     (const Vector2 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vector2__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vector2__pack_to_buffer
                     (const Vector2 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vector2__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vector2 *
       vector2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vector2 *)
     protobuf_c_message_unpack (&vector2__descriptor,
                                allocator, len, data);
}
void   vector2__free_unpacked
                     (Vector2 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vector2__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vector3__init
                     (Vector3         *message)
{
  static const Vector3 init_value = VECTOR3__INIT;
  *message = init_value;
}
size_t vector3__get_packed_size
                     (const Vector3 *message)
{
  assert(message->base.descriptor == &vector3__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vector3__pack
                     (const Vector3 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vector3__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vector3__pack_to_buffer
                     (const Vector3 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vector3__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vector3 *
       vector3__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vector3 *)
     protobuf_c_message_unpack (&vector3__descriptor,
                                allocator, len, data);
}
void   vector3__free_unpacked
                     (Vector3 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vector3__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   robot_id__init
                     (RobotId         *message)
{
  static const RobotId init_value = ROBOT_ID__INIT;
  *message = init_value;
}
size_t robot_id__get_packed_size
                     (const RobotId *message)
{
  assert(message->base.descriptor == &robot_id__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t robot_id__pack
                     (const RobotId *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &robot_id__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t robot_id__pack_to_buffer
                     (const RobotId *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &robot_id__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RobotId *
       robot_id__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RobotId *)
     protobuf_c_message_unpack (&robot_id__descriptor,
                                allocator, len, data);
}
void   robot_id__free_unpacked
                     (RobotId *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &robot_id__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tracked_ball__init
                     (TrackedBall         *message)
{
  static const TrackedBall init_value = TRACKED_BALL__INIT;
  *message = init_value;
}
size_t tracked_ball__get_packed_size
                     (const TrackedBall *message)
{
  assert(message->base.descriptor == &tracked_ball__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tracked_ball__pack
                     (const TrackedBall *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tracked_ball__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tracked_ball__pack_to_buffer
                     (const TrackedBall *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tracked_ball__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrackedBall *
       tracked_ball__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrackedBall *)
     protobuf_c_message_unpack (&tracked_ball__descriptor,
                                allocator, len, data);
}
void   tracked_ball__free_unpacked
                     (TrackedBall *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tracked_ball__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   kicked_ball__init
                     (KickedBall         *message)
{
  static const KickedBall init_value = KICKED_BALL__INIT;
  *message = init_value;
}
size_t kicked_ball__get_packed_size
                     (const KickedBall *message)
{
  assert(message->base.descriptor == &kicked_ball__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t kicked_ball__pack
                     (const KickedBall *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &kicked_ball__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t kicked_ball__pack_to_buffer
                     (const KickedBall *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &kicked_ball__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
KickedBall *
       kicked_ball__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (KickedBall *)
     protobuf_c_message_unpack (&kicked_ball__descriptor,
                                allocator, len, data);
}
void   kicked_ball__free_unpacked
                     (KickedBall *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &kicked_ball__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tracked_robot__init
                     (TrackedRobot         *message)
{
  static const TrackedRobot init_value = TRACKED_ROBOT__INIT;
  *message = init_value;
}
size_t tracked_robot__get_packed_size
                     (const TrackedRobot *message)
{
  assert(message->base.descriptor == &tracked_robot__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tracked_robot__pack
                     (const TrackedRobot *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tracked_robot__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tracked_robot__pack_to_buffer
                     (const TrackedRobot *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tracked_robot__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrackedRobot *
       tracked_robot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrackedRobot *)
     protobuf_c_message_unpack (&tracked_robot__descriptor,
                                allocator, len, data);
}
void   tracked_robot__free_unpacked
                     (TrackedRobot *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tracked_robot__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tracked_frame__init
                     (TrackedFrame         *message)
{
  static const TrackedFrame init_value = TRACKED_FRAME__INIT;
  *message = init_value;
}
size_t tracked_frame__get_packed_size
                     (const TrackedFrame *message)
{
  assert(message->base.descriptor == &tracked_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tracked_frame__pack
                     (const TrackedFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tracked_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tracked_frame__pack_to_buffer
                     (const TrackedFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tracked_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrackedFrame *
       tracked_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrackedFrame *)
     protobuf_c_message_unpack (&tracked_frame__descriptor,
                                allocator, len, data);
}
void   tracked_frame__free_unpacked
                     (TrackedFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tracked_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor vector2__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vector2, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vector2, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vector2__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange vector2__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vector2__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Vector2",
  "Vector2",
  "Vector2",
  "",
  sizeof(Vector2),
  2,
  vector2__field_descriptors,
  vector2__field_indices_by_name,
  1,  vector2__number_ranges,
  (ProtobufCMessageInit) vector2__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vector3__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vector3, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vector3, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Vector3, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vector3__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange vector3__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vector3__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Vector3",
  "Vector3",
  "Vector3",
  "",
  sizeof(Vector3),
  3,
  vector3__field_descriptors,
  vector3__field_indices_by_name,
  1,  vector3__number_ranges,
  (ProtobufCMessageInit) vector3__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor robot_id__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(RobotId, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "team_color",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RobotId, team_color),
    &team_color__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned robot_id__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = team_color */
};
static const ProtobufCIntRange robot_id__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor robot_id__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RobotId",
  "RobotId",
  "RobotId",
  "",
  sizeof(RobotId),
  2,
  robot_id__field_descriptors,
  robot_id__field_indices_by_name,
  1,  robot_id__number_ranges,
  (ProtobufCMessageInit) robot_id__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tracked_ball__field_descriptors[3] =
{
  {
    "pos",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TrackedBall, pos),
    &vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vel",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TrackedBall, vel),
    &vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "visibility",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(TrackedBall, has_visibility),
    offsetof(TrackedBall, visibility),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tracked_ball__field_indices_by_name[] = {
  0,   /* field[0] = pos */
  1,   /* field[1] = vel */
  2,   /* field[2] = visibility */
};
static const ProtobufCIntRange tracked_ball__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tracked_ball__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TrackedBall",
  "TrackedBall",
  "TrackedBall",
  "",
  sizeof(TrackedBall),
  3,
  tracked_ball__field_descriptors,
  tracked_ball__field_indices_by_name,
  1,  tracked_ball__number_ranges,
  (ProtobufCMessageInit) tracked_ball__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor kicked_ball__field_descriptors[6] =
{
  {
    "pos",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(KickedBall, pos),
    &vector2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vel",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(KickedBall, vel),
    &vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_timestamp",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(KickedBall, start_timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop_timestamp",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(KickedBall, has_stop_timestamp),
    offsetof(KickedBall, stop_timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop_pos",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(KickedBall, stop_pos),
    &vector2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "robot_id",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(KickedBall, robot_id),
    &robot_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned kicked_ball__field_indices_by_name[] = {
  0,   /* field[0] = pos */
  5,   /* field[5] = robot_id */
  2,   /* field[2] = start_timestamp */
  4,   /* field[4] = stop_pos */
  3,   /* field[3] = stop_timestamp */
  1,   /* field[1] = vel */
};
static const ProtobufCIntRange kicked_ball__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor kicked_ball__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "KickedBall",
  "KickedBall",
  "KickedBall",
  "",
  sizeof(KickedBall),
  6,
  kicked_ball__field_descriptors,
  kicked_ball__field_indices_by_name,
  1,  kicked_ball__number_ranges,
  (ProtobufCMessageInit) kicked_ball__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tracked_robot__field_descriptors[6] =
{
  {
    "robot_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TrackedRobot, robot_id),
    &robot_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TrackedRobot, pos),
    &vector2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orientation",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(TrackedRobot, orientation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vel",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TrackedRobot, vel),
    &vector2__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vel_angular",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(TrackedRobot, has_vel_angular),
    offsetof(TrackedRobot, vel_angular),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "visibility",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(TrackedRobot, has_visibility),
    offsetof(TrackedRobot, visibility),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tracked_robot__field_indices_by_name[] = {
  2,   /* field[2] = orientation */
  1,   /* field[1] = pos */
  0,   /* field[0] = robot_id */
  3,   /* field[3] = vel */
  4,   /* field[4] = vel_angular */
  5,   /* field[5] = visibility */
};
static const ProtobufCIntRange tracked_robot__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor tracked_robot__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TrackedRobot",
  "TrackedRobot",
  "TrackedRobot",
  "",
  sizeof(TrackedRobot),
  6,
  tracked_robot__field_descriptors,
  tracked_robot__field_indices_by_name,
  1,  tracked_robot__number_ranges,
  (ProtobufCMessageInit) tracked_robot__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tracked_frame__field_descriptors[6] =
{
  {
    "frame_number",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TrackedFrame, frame_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(TrackedFrame, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "balls",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrackedFrame, n_balls),
    offsetof(TrackedFrame, balls),
    &tracked_ball__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "robots",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TrackedFrame, n_robots),
    offsetof(TrackedFrame, robots),
    &tracked_robot__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kicked_ball",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TrackedFrame, kicked_ball),
    &kicked_ball__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "capabilities",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(TrackedFrame, n_capabilities),
    offsetof(TrackedFrame, capabilities),
    &capability__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tracked_frame__field_indices_by_name[] = {
  2,   /* field[2] = balls */
  5,   /* field[5] = capabilities */
  0,   /* field[0] = frame_number */
  4,   /* field[4] = kicked_ball */
  3,   /* field[3] = robots */
  1,   /* field[1] = timestamp */
};
static const ProtobufCIntRange tracked_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor tracked_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TrackedFrame",
  "TrackedFrame",
  "TrackedFrame",
  "",
  sizeof(TrackedFrame),
  6,
  tracked_frame__field_descriptors,
  tracked_frame__field_indices_by_name,
  1,  tracked_frame__number_ranges,
  (ProtobufCMessageInit) tracked_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue team_color__enum_values_by_number[3] =
{
  { "TEAM_COLOR_UNKNOWN", "TEAM_COLOR__TEAM_COLOR_UNKNOWN", 0 },
  { "TEAM_COLOR_YELLOW", "TEAM_COLOR__TEAM_COLOR_YELLOW", 1 },
  { "TEAM_COLOR_BLUE", "TEAM_COLOR__TEAM_COLOR_BLUE", 2 },
};
static const ProtobufCIntRange team_color__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex team_color__enum_values_by_name[3] =
{
  { "TEAM_COLOR_BLUE", 2 },
  { "TEAM_COLOR_UNKNOWN", 0 },
  { "TEAM_COLOR_YELLOW", 1 },
};
const ProtobufCEnumDescriptor team_color__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TeamColor",
  "TeamColor",
  "TeamColor",
  "",
  3,
  team_color__enum_values_by_number,
  3,
  team_color__enum_values_by_name,
  1,
  team_color__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue capability__enum_values_by_number[4] =
{
  { "CAPABILITY_UNKNOWN", "CAPABILITY__CAPABILITY_UNKNOWN", 0 },
  { "CAPABILITY_DETECT_FLYING_BALLS", "CAPABILITY__CAPABILITY_DETECT_FLYING_BALLS", 1 },
  { "CAPABILITY_DETECT_MULTIPLE_BALLS", "CAPABILITY__CAPABILITY_DETECT_MULTIPLE_BALLS", 2 },
  { "CAPABILITY_DETECT_KICKED_BALLS", "CAPABILITY__CAPABILITY_DETECT_KICKED_BALLS", 3 },
};
static const ProtobufCIntRange capability__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex capability__enum_values_by_name[4] =
{
  { "CAPABILITY_DETECT_FLYING_BALLS", 1 },
  { "CAPABILITY_DETECT_KICKED_BALLS", 3 },
  { "CAPABILITY_DETECT_MULTIPLE_BALLS", 2 },
  { "CAPABILITY_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor capability__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Capability",
  "Capability",
  "Capability",
  "",
  4,
  capability__enum_values_by_number,
  4,
  capability__enum_values_by_name,
  1,
  capability__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
