/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_wrapper.proto */

#ifndef PROTOBUF_C_messages_5frobocup_5fssl_5fwrapper_2eproto__INCLUDED
#define PROTOBUF_C_messages_5frobocup_5fssl_5fwrapper_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif

#include "messages_robocup_ssl_detection.pb-c.h"
#include "messages_robocup_ssl_geometry.pb-c.h"

typedef struct SSLWrapperPacket SSLWrapperPacket;


/* --- enums --- */

typedef enum _SSLSource {
  SSL__SOURCE__SSL_SOURCE_UNKNOWN = 0,
  SSL__SOURCE__SSL_SOURCE_OTHER = 1,
  SSL__SOURCE__SSL_SOURCE_SSL_VISION = 2,
  SSL__SOURCE__SSL_SOURCE_VISION_PROCESSOR = 3,
  SSL__SOURCE__SSL_SOURCE_GRSIM = 4,
  SSL__SOURCE__SSL_SOURCE_ERFORCE_SIM = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SSL__SOURCE)
} SSLSource;

/* --- messages --- */

struct  SSLWrapperPacket
{
  ProtobufCMessage base;
  SSLDetectionFrame *detection;
  SSLGeometryData *geometry;
  protobuf_c_boolean has_source;
  SSLSource source;
};
#define SSL__WRAPPER_PACKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ssl__wrapper_packet__descriptor) \
, NULL, NULL, 0, SSL__SOURCE__SSL_SOURCE_UNKNOWN }


/* SSLWrapperPacket methods */
void   ssl__wrapper_packet__init
                     (SSLWrapperPacket         *message);
size_t ssl__wrapper_packet__get_packed_size
                     (const SSLWrapperPacket   *message);
size_t ssl__wrapper_packet__pack
                     (const SSLWrapperPacket   *message,
                      uint8_t             *out);
size_t ssl__wrapper_packet__pack_to_buffer
                     (const SSLWrapperPacket   *message,
                      ProtobufCBuffer     *buffer);
SSLWrapperPacket *
       ssl__wrapper_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ssl__wrapper_packet__free_unpacked
                     (SSLWrapperPacket *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SSLWrapperPacket_Closure)
                 (const SSLWrapperPacket *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    ssl__source__descriptor;
extern const ProtobufCMessageDescriptor ssl__wrapper_packet__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messages_5frobocup_5fssl_5fwrapper_2eproto__INCLUDED */
