/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_detection.proto */

#ifndef PROTOBUF_C_messages_5frobocup_5fssl_5fdetection_2eproto__INCLUDED
#define PROTOBUF_C_messages_5frobocup_5fssl_5fdetection_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct SSLDetectionBall SSLDetectionBall;
typedef struct SSLDetectionRobot SSLDetectionRobot;
typedef struct SSLDetectionFrame SSLDetectionFrame;


/* --- enums --- */


/* --- messages --- */

struct  SSLDetectionBall
{
  ProtobufCMessage base;
  /*
   * Confidence in [0-1] of the detection
   */
  float confidence;
  protobuf_c_boolean has_area;
  uint32_t area;
  /*
   * X-coordinate in [mm] in global ssl-vision coordinate system
   */
  float x;
  /*
   * Y-coordinate in [mm] in global ssl-vision coordinate system
   */
  float y;
  /*
   * Z-coordinate in [mm] in global ssl-vision coordinate system
   * Not supported by ssl-vision, but might be set by simulators
   */
  protobuf_c_boolean has_z;
  float z;
  /*
   * X-coordinate in [pixel] in the image
   */
  float pixel_x;
  /*
   * Y-coordinate in [pixel] in the image
   */
  float pixel_y;
};
#define SSL__DETECTION_BALL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ssl__detection_ball__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  SSLDetectionRobot
{
  ProtobufCMessage base;
  /*
   * Confidence in [0-1] of the detection
   */
  float confidence;
  /*
   * Id of the robot
   */
  protobuf_c_boolean has_robot_id;
  uint32_t robot_id;
  /*
   * X-coordinate in [mm] in global ssl-vision coordinate system
   */
  float x;
  /*
   * Y-coordinate in [mm] in global ssl-vision coordinate system
   */
  float y;
  /*
   * Orientation in [rad]
   */
  protobuf_c_boolean has_orientation;
  float orientation;
  /*
   * X-coordinate in [pixel] in the image
   */
  float pixel_x;
  /*
   * Y-coordinate in [pixel] in the image
   */
  float pixel_y;
  /*
   * Height, as configured in ssl-vision for the respective team
   */
  protobuf_c_boolean has_height;
  float height;
};
#define SSL__DETECTION_ROBOT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ssl__detection_robot__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  SSLDetectionFrame
{
  ProtobufCMessage base;
  /*
   * monotonously increasing frame number
   */
  uint32_t frame_number;
  /*
   * Unix timestamp in [seconds] at which the image has been received by ssl-vision
   */
  double t_capture;
  /*
   * Unix timestamp in [seconds] at which this message has been sent to the network
   */
  double t_sent;
  /*
   * Camera timestamp in [seconds] as reported by the camera, if supported
   * This is not necessarily a unix timestamp
   */
  protobuf_c_boolean has_t_capture_camera;
  double t_capture_camera;
  /*
   * Identifier of the camera
   */
  uint32_t camera_id;
  /*
   * Detected balls
   */
  size_t n_balls;
  SSLDetectionBall **balls;
  /*
   * Detected yellow robots
   */
  size_t n_robots_yellow;
  SSLDetectionRobot **robots_yellow;
  /*
   * Detected blue robots
   */
  size_t n_robots_blue;
  SSLDetectionRobot **robots_blue;
};
#define SSL__DETECTION_FRAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ssl__detection_frame__descriptor) \
, 0, 0, 0, 0, 0, 0, 0,NULL, 0,NULL, 0,NULL }


/* SSLDetectionBall methods */
void   ssl__detection_ball__init
                     (SSLDetectionBall         *message);
size_t ssl__detection_ball__get_packed_size
                     (const SSLDetectionBall   *message);
size_t ssl__detection_ball__pack
                     (const SSLDetectionBall   *message,
                      uint8_t             *out);
size_t ssl__detection_ball__pack_to_buffer
                     (const SSLDetectionBall   *message,
                      ProtobufCBuffer     *buffer);
SSLDetectionBall *
       ssl__detection_ball__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ssl__detection_ball__free_unpacked
                     (SSLDetectionBall *message,
                      ProtobufCAllocator *allocator);
/* SSLDetectionRobot methods */
void   ssl__detection_robot__init
                     (SSLDetectionRobot         *message);
size_t ssl__detection_robot__get_packed_size
                     (const SSLDetectionRobot   *message);
size_t ssl__detection_robot__pack
                     (const SSLDetectionRobot   *message,
                      uint8_t             *out);
size_t ssl__detection_robot__pack_to_buffer
                     (const SSLDetectionRobot   *message,
                      ProtobufCBuffer     *buffer);
SSLDetectionRobot *
       ssl__detection_robot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ssl__detection_robot__free_unpacked
                     (SSLDetectionRobot *message,
                      ProtobufCAllocator *allocator);
/* SSLDetectionFrame methods */
void   ssl__detection_frame__init
                     (SSLDetectionFrame         *message);
size_t ssl__detection_frame__get_packed_size
                     (const SSLDetectionFrame   *message);
size_t ssl__detection_frame__pack
                     (const SSLDetectionFrame   *message,
                      uint8_t             *out);
size_t ssl__detection_frame__pack_to_buffer
                     (const SSLDetectionFrame   *message,
                      ProtobufCBuffer     *buffer);
SSLDetectionFrame *
       ssl__detection_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ssl__detection_frame__free_unpacked
                     (SSLDetectionFrame *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SSLDetectionBall_Closure)
                 (const SSLDetectionBall *message,
                  void *closure_data);
typedef void (*SSLDetectionRobot_Closure)
                 (const SSLDetectionRobot *message,
                  void *closure_data);
typedef void (*SSLDetectionFrame_Closure)
                 (const SSLDetectionFrame *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ssl__detection_ball__descriptor;
extern const ProtobufCMessageDescriptor ssl__detection_robot__descriptor;
extern const ProtobufCMessageDescriptor ssl__detection_frame__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messages_5frobocup_5fssl_5fdetection_2eproto__INCLUDED */
