/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages_robocup_ssl_wrapper.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages_robocup_ssl_wrapper.pb-c.h"
void   ssl__wrapper_packet__init
                     (SSLWrapperPacket         *message)
{
  static const SSLWrapperPacket init_value = SSL__WRAPPER_PACKET__INIT;
  *message = init_value;
}
size_t ssl__wrapper_packet__get_packed_size
                     (const SSLWrapperPacket *message)
{
  assert(message->base.descriptor == &ssl__wrapper_packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ssl__wrapper_packet__pack
                     (const SSLWrapperPacket *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ssl__wrapper_packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ssl__wrapper_packet__pack_to_buffer
                     (const SSLWrapperPacket *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ssl__wrapper_packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SSLWrapperPacket *
       ssl__wrapper_packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SSLWrapperPacket *)
     protobuf_c_message_unpack (&ssl__wrapper_packet__descriptor,
                                allocator, len, data);
}
void   ssl__wrapper_packet__free_unpacked
                     (SSLWrapperPacket *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ssl__wrapper_packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ssl__wrapper_packet__field_descriptors[3] =
{
  {
    "detection",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLWrapperPacket, detection),
    &ssl__detection_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geometry",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SSLWrapperPacket, geometry),
    &ssl__geometry_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(SSLWrapperPacket, has_source),
    offsetof(SSLWrapperPacket, source),
    &ssl__source__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ssl__wrapper_packet__field_indices_by_name[] = {
  0,   /* field[0] = detection */
  1,   /* field[1] = geometry */
  2,   /* field[2] = source */
};
static const ProtobufCIntRange ssl__wrapper_packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ssl__wrapper_packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SSL_WrapperPacket",
  "SSLWrapperPacket",
  "SSLWrapperPacket",
  "",
  sizeof(SSLWrapperPacket),
  3,
  ssl__wrapper_packet__field_descriptors,
  ssl__wrapper_packet__field_indices_by_name,
  1,  ssl__wrapper_packet__number_ranges,
  (ProtobufCMessageInit) ssl__wrapper_packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ssl__source__enum_values_by_number[6] =
{
  { "SSL_SOURCE_UNKNOWN", "SSL__SOURCE__SSL_SOURCE_UNKNOWN", 0 },
  { "SSL_SOURCE_OTHER", "SSL__SOURCE__SSL_SOURCE_OTHER", 1 },
  { "SSL_SOURCE_SSL_VISION", "SSL__SOURCE__SSL_SOURCE_SSL_VISION", 2 },
  { "SSL_SOURCE_VISION_PROCESSOR", "SSL__SOURCE__SSL_SOURCE_VISION_PROCESSOR", 3 },
  { "SSL_SOURCE_GRSIM", "SSL__SOURCE__SSL_SOURCE_GRSIM", 4 },
  { "SSL_SOURCE_ERFORCE_SIM", "SSL__SOURCE__SSL_SOURCE_ERFORCE_SIM", 5 },
};
static const ProtobufCIntRange ssl__source__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex ssl__source__enum_values_by_name[6] =
{
  { "SSL_SOURCE_ERFORCE_SIM", 5 },
  { "SSL_SOURCE_GRSIM", 4 },
  { "SSL_SOURCE_OTHER", 1 },
  { "SSL_SOURCE_SSL_VISION", 2 },
  { "SSL_SOURCE_UNKNOWN", 0 },
  { "SSL_SOURCE_VISION_PROCESSOR", 3 },
};
const ProtobufCEnumDescriptor ssl__source__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "SSL_Source",
  "SSL_Source",
  "SSLSource",
  "",
  6,
  ssl__source__enum_values_by_number,
  6,
  ssl__source__enum_values_by_name,
  1,
  ssl__source__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
